# Generated by Django 4.2.20 on 2025-12-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answers', models.JSONField(default=list)),
                ('correct_index', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('time_limit', models.PositiveIntegerField(default=30)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='NIRD.quiz')),
            ],
        ),
    ]
