# Generated by Django 4.2.20 on 2025-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIRD', '0002_userquizattempt_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='selected_questions',
            field=models.JSONField(default=list),
        ),
    ]
